<wsdl:definitions
     name="dbReference_CallProcAcco"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CacheJobsApp/AccoCacheJobsTriggerService/dbReference_CallProcAcco"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CacheJobsApp/AccoCacheJobsTriggerService/dbReference_CallProcAcco"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbReference_CallProcAcco"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbReference_CallProcAcco_plt" >
    <plt:role name="dbReference_CallProcAcco_role" >
      <plt:portType name="tns:dbReference_CallProcAcco_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbReference_CallProcAcco"
               schemaLocation="../Schemas/dbReference_CallProcAcco_sp.xsd" />
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="dbReference_CallProcAcco_ptt">
        <wsdl:operation name="dbReference_CallProcAcco">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
