<wsdl:definitions
     name="dbReference_QueryJobsAcco"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CacheJobsApp/AccoCacheJobsTriggerService/dbReference_QueryJobsAcco"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CacheJobsApp/AccoCacheJobsTriggerService/dbReference_QueryJobsAcco"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference_QueryJobsAcco"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbReference_QueryJobsAcco_plt" >
    <plt:role name="dbReference_QueryJobsAcco_role" >
      <plt:portType name="tns:dbReference_QueryJobsAcco_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference_QueryJobsAcco" schemaLocation="../Schemas/dbReference_QueryJobsAcco_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="dbReference_QueryJobsAccoSelect_inputParameters">
        <wsdl:part name="dbReference_QueryJobsAccoSelect_inputParameters" element="top:dbReference_QueryJobsAccoSelect_JobSeq_RowCountInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CachejobsaccoCollection_msg">
        <wsdl:part name="CachejobsaccoCollection" element="top:CachejobsaccoCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbReference_QueryJobsAcco_ptt">
        <wsdl:operation name="dbReference_QueryJobsAccoSelect">
            <wsdl:input message="tns:dbReference_QueryJobsAccoSelect_inputParameters"/>
            <wsdl:output message="tns:CachejobsaccoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
