INSERT INTO "C##TRAVELOGIX"."CACHEJOBSDEFNACCO" (SUPPID, CREDNAME, COUNTRYCODE, CITYCODE, BOOKDAYSRANGE, ROOMSRANGE, ADULTGUESTSRANGE, CHILDGUESTSRANGE, TRIPDURRANGE) VALUES ('DESIYA', 'B2B', 'IN', 'G1011', '2', '2', '2', '0', '2');
INSERT INTO "C##TRAVELOGIX"."CACHEJOBSDEFNACCO" (SUPPID, CREDNAME, COUNTRYCODE, CITYCODE, BOOKDAYSRANGE, ROOMSRANGE, ADULTGUESTSRANGE, CHILDGUESTSRANGE, TRIPDURRANGE) VALUES ('DOTW', 'B2B', 'IN', 'G1011', '2', '2', '2', '0', '2');

INSERT INTO "C##TRAVELOGIX"."CACHEJOBSDEFNAIR" (SUPPID, CREDNAME, ORIGIN, DESTINATION, TRIPTYPE, CABINCLASS, BOOKDAYSRANGE, TRIPDURRANGE, ADULTPSGRSRANGE, CHILDPSGRSRANGE, INFANTPSGRSRANGE) VALUES ('INDIGO', 'B2B', 'BLR', 'HYD', 'OneWay', 'Economy', '2', '2', '1', '0', '0');


COMMIT;