<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://www.coxandkings.com/integ/suppl/common"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://www.coxandkings.com/integ/suppl/cache/trigger"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:tns="http://www.coxandkings.com/integ/suppl/acco"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns3="http://xmlns.oracle.com/CacheJobsApp/AccoTriggeredCacheJobService/SupplierCredentialsServiceREST"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://www.opentravel.org/OTA/2003/05" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns4="http://www.coxandkings.com/integ/suppl/acco/AccoBusinessAsyncService"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/jms/CacheJobsApp/AccoTriggeredCacheJobService/jmsReference_CacheJobsAccoQueue">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/jmsReference_CacheJobsAccoQueue.wsdl"/>
        <oracle-xsl-mapper:rootElement name="AccoCacheJobTriggerMessage"
                                       namespace="http://www.coxandkings.com/integ/suppl/cache/trigger"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/supplier/Accommodation/common/WSDLs/AccoBusinessAsyncService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="AccoBusinessServiceRQ"
                                       namespace="http://www.coxandkings.com/integ/suppl/acco"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON AUG 08 14:02:55 IST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:AccoBusinessServiceRQ>
      <tns:RequestHeader>
        <ns1:UserID>Caching</ns1:UserID>
        <ns1:SessionID>
          <xsl:value-of select='concat ("CacheSession-", xp20:current-dateTime ( ) )'/>
        </ns1:SessionID>
        <ns1:TransactionID>
          <xsl:value-of select='concat (/ns0:AccoCacheJobTriggerMessage/ns0:AccoCacheJobElements/ns0:JobSequence, "-", xp20:current-dateTime ( ) )'/>
        </ns1:TransactionID>
        <ns1:SupplierCredentialsList>
          <ns1:SupplierCredentials>
            <ns1:SupplierID>
              <xsl:value-of select="/ns0:AccoCacheJobTriggerMessage/ns0:SupplierCredentials/ns1:SupplierID"/>
            </ns1:SupplierID>
            <ns1:SearchType>
              <xsl:value-of select="/ns0:AccoCacheJobTriggerMessage/ns0:SupplierCredentials/ns1:SearchType"/>
            </ns1:SearchType>
            <xsl:copy-of select="/ns0:AccoCacheJobTriggerMessage/ns0:SupplierCredentials/ns1:Credentials"/>
          </ns1:SupplierCredentials>
        </ns1:SupplierCredentialsList>
      </tns:RequestHeader>
      <tns:RequestBody>
        <ns2:OTA_HotelAvailRQ RequestedCurrency="INR" Target="Test" Version="1.000" PrimaryLangID="EN">
          <ns2:AvailRequestSegments>
            <ns2:AvailRequestSegment>
              <ns2:HotelSearchCriteria>
                <ns2:Criterion>
                  <ns2:RefPoint CountryCode="{/ns0:AccoCacheJobTriggerMessage/ns0:AccoCacheJobElements/ns0:CountryCode}"/>
                  <ns2:HotelRef HotelCityCode="{/ns0:AccoCacheJobTriggerMessage/ns0:AccoCacheJobElements/ns0:CityCode}"/>
                  <ns2:StayDateRange Start="{/ns0:AccoCacheJobTriggerMessage/ns0:AccoCacheJobElements/ns0:StartDate}"
                                     End="{/ns0:AccoCacheJobTriggerMessage/ns0:AccoCacheJobElements/ns0:EndDate}"/>
                  <ns2:RoomStayCandidates>
                    <xsl:call-template name="roomStay">
                      <xsl:with-param name="startIndex">1</xsl:with-param>
                      <xsl:with-param name="roomCount"
                                      select="/ns0:AccoCacheJobTriggerMessage/ns0:AccoCacheJobElements/ns0:Rooms"/>
                      <xsl:with-param name="adultCount"
                                      select="/ns0:AccoCacheJobTriggerMessage/ns0:AccoCacheJobElements/ns0:AdultGuests"/>
                      <xsl:with-param name="childCount"
                                      select="/ns0:AccoCacheJobTriggerMessage/ns0:AccoCacheJobElements/ns0:ChildGuests"/>
                    </xsl:call-template>
                  </ns2:RoomStayCandidates>
                </ns2:Criterion>
              </ns2:HotelSearchCriteria>
            </ns2:AvailRequestSegment>
          </ns2:AvailRequestSegments>
        </ns2:OTA_HotelAvailRQ>
      </tns:RequestBody>
    </tns:AccoBusinessServiceRQ>
  </xsl:template>
  <xsl:template name="roomStay">
    <xsl:param name="startIndex"/>
    <xsl:param name="roomCount"/>
    <xsl:param name="adultCount"/>
    <xsl:param name="childCount"/>
    <xsl:if test="$startIndex &lt;= $roomCount">
      <ns2:RoomStayCandidate RPH="{$startIndex}">
        <ns2:GuestCounts>
          <xsl:call-template name="guestCounts-adult">
            <xsl:with-param name="adultCount">
							<xsl:choose>
                <xsl:when test="(($startIndex = 1) and (($adultCount mod $roomCount) > 0))">
                  <xsl:value-of select="floor($adultCount div $roomCount) + 1"/>
                </xsl:when>
                <xsl:otherwise>
                  <xsl:value-of select="floor($adultCount div $roomCount)"/>
                </xsl:otherwise>
              </xsl:choose>
					</xsl:with-param>
          </xsl:call-template>
        </ns2:GuestCounts>
      </ns2:RoomStayCandidate>
    </xsl:if>
    <xsl:if test="$startIndex &lt;= $roomCount">
      <xsl:call-template name="roomStay">
        <xsl:with-param name="startIndex">
				<xsl:value-of select="$startIndex + 1"/>
			</xsl:with-param>
        <xsl:with-param name="roomCount">
				<xsl:value-of select="$roomCount"/>
			</xsl:with-param>
        <xsl:with-param name="adultCount">
				<xsl:value-of select="$adultCount"/>
			</xsl:with-param>
        <xsl:with-param name="childCount">
				<xsl:value-of select="$childCount"/>
			</xsl:with-param>
      </xsl:call-template>
    </xsl:if>
  </xsl:template>
  <xsl:template name="guestCounts-adult">
    <xsl:param name="adultCount"/>
    <ns2:GuestCount AgeQualifyingCode="10" Count="{$adultCount}"/>
  </xsl:template>
</xsl:stylesheet>
